# Generated by Django 5.0.3 on 2024-03-13 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('completed', 'Завершен')], default='created', max_length=10, verbose_name='Статус')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('confirmation_time', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Картинка')),
                ('content', models.TextField(verbose_name='Контент')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('card', 'Карта'), ('bank_transfer', 'Банковский перевод'), ('paypal', 'PayPal')], default='card', max_length=20, verbose_name='Тип оплаты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.order', verbose_name='Заказ')),
            ],
        ),
    ]
