# Generated by Django 3.2.4 on 2024-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
    ]
